{{ if .Values.StorageClass.create -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.StorageClass.name }}
{{- if .Values.StorageClass.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ template "nfs-full-provisioner.provisionerName" . }}
allowVolumeExpansion: {{ .Values.StorageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.StorageClass.reclaimPolicy }}
{{- if .Values.nfs.mountOptions }}
mountOptions:
  {{- range .Values.nfs.mountOptions }}
  - {{ . }}
  {{- end }}
{{- end }}
{{ end -}}