apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nfs-full-provisioner.serviceAccountName" . }}
imagePullSecrets: 
- name: sa-{{ .Release.Namespace }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "nfs-full-provisioner.fullname" . }}
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: {{ template "nfs-full-provisioner.name" . }}
    release: {{ .Release.Name }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "nfs-full-provisioner.fullname" . }}
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "nfs-full-provisioner.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }} 
  template:
    metadata:
      labels:
        app: {{ template "nfs-full-provisioner.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "nfs-full-provisioner.serviceAccountName" . }}
      nodeSelector:
         kubernetes.io/hostname: {{ .Values.nfs.server }}
      {{- if .Values.priorityClass.run }}
      priorityClassName: {{ .Values.priorityClass.name | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner={{ template "nfs-full-provisioner.provisionerName" . }}"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: {{ template "nfs-full-provisioner.fullname" . }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
          {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
      volumes:
        - name: export-volume
          hostPath:
            path: {{ .Values.nfs.path }}
