{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  metadata:
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nfs-full-provisioner.fullname" . }}-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
{{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["full-nfs-provisioner"]
    verbs: ["use"]
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: run-{{ template "nfs-full-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nfs-full-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "nfs-full-provisioner.fullname" . }}-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: leader-locking-{{ template "nfs-full-provisioner.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
{{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups:      ['extensions']
    resources:      ['podsecuritypolicies']
    verbs:          ['use']
    resourceNames:  [{{ template "nfs-full-provisioner.fullname" . }}]
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "nfs-full-provisioner.name" . }}
    chart: {{ template "nfs-full-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: leader-locking-{{ template "nfs-full-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nfs-full-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: leader-locking-{{ template "nfs-full-provisioner.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}