{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: sa-{{ .Release.Namespace }}
metadata:
  labels:
    app: {{ template "nfs-client-provisioner.name" . }}
    chart: {{ template "nfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nfs-client-provisioner.serviceAccountName" . }}
{{- end -}}
