# Default values for nfs-client-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategyType: Recreate

image:
  repository: nfs-client-provisioner
  tag: latest
  pullPolicy: IfNotPresent

busyboximage:
  repository: busybox
  tag: 1.31
  pullPolicy: IfNotPresent

nfs:
  server:
  path: /export/nfs-dynamic-k8s
  mountOptions:

# For creating the StorageClass automatically:
StorageClass:
  create: true
  
  # Set a StorageClass name
  # Ignored if StorageClass.create is false
  name: managed-nfs-storage

  # Set a provisioner name. If unset, a name will be generated.
  provisionerName: nfs.io/nfs-client-provisioner

  # Set StorageClass as the default StorageClass
  # Ignored if StorageClass.create is false
  defaultClass: true

  # Allow volume to be expanded dynamically
  allowVolumeExpansion: true

  # Method used to reclaim an obsoleted volume
  reclaimPolicy: Delete

  # When set to false your PVs will not be archived by the provisioner upon deletion of the PVC.
  archiveOnDelete: false

## For RBAC support:
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# If true, create & use Pod Security Policy resources
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/
podSecurityPolicy:
  enabled: true

## Decide whether or not to run with priorityClass of priorityClassName system-cluster-critical.
priorityClass:

  run: true
  name: system-cluster-critical

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true

  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
